server:
  port: 8003
spring:
  application:
    name: cloud-consumer-feign

# eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://flomesh:123456@localhost:8761/eureka
  instance:
    instance-id: cloud-consumer-feign-hystrix #修改Eureka上的默认描述信息