FROM openjdk:8-jdk-alpine
VOLUME /tmp
ADD cloud-provider2/target/cloud-provider2-1.0.0.jar app.jar
ENTRYPOINT ["java","-jar","app.jar","-Dspring.config.location=file:///config/application.yml"]
EXPOSE 7902