server:
  port: 8002
  servlet:
    context-path:
spring:
  application:
    name: cloud-consumer-feign

# eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://flomesh:123456@localhost:8761/eureka
  instance:
    instance-id: cloud-consumer-feign #修改Eureka上的默认描述信息

